### ISSUE TITLE
NoMethodError at /create undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by TheJarX** [julionav/lazyrecord#4]
Al eliminar la el archivo donde se almacena la info y al intentar, luego, usar el método `create`

**Comment by julionav** [comment]
It looks like the problem is caused because you deleted the file where the data is located and didn't restart the server.

I think this is an ok situation, I haven't tried but my guess is that if you delete an SQLite database while there is still a connection to it, something will start malfunctioning.

A solution fo this would be to always create a new connection to the `pstore` file on each request, which is not possible yet 🤔
